//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersianDataAnnotationsCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataAnnotationsResourcesFa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotationsResourcesFa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersianDataAnnotationsCore.DataAnnotationsResourcesFa", typeof(DataAnnotationsResourcesFa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرگمان &apos;{0}&apos; نمی تواند null یا empty یا فقط white space باشد.
        /// </summary>
        internal static string ArgumentIsNullOrWhitespace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متادیتای نوع &apos;{0}&apos; حاوی property یا feild های ناشناس {1} است. لطفا مطمئن شوید که name مربوط به member ها با name مربوط به property ها رو type اصلی یکی باشد..
        /// </summary>
        internal static string AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties {
            get {
                return ResourceManager.GetString("AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع &apos;{0}&apos;باید public باشد.
        /// </summary>
        internal static string AttributeStore_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("AttributeStore_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع &apos;{0}&apos; شامل یک متد public با نام &apos;{1}&apos; نیست.
        /// </summary>
        internal static string AttributeStore_Unknown_Method {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع &apos;{0}&apos; شامل یک پراپرتی public با نام &apos;{1}&apos; نیست.
        /// </summary>
        internal static string AttributeStore_Unknown_Property {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار نمی تواند خالی یا تهی باشد.
        /// </summary>
        internal static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پراپرتی {0}.{1} یافت نشد.
        /// </summary>
        internal static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} و {1} با هم یکسان نیستند.
        /// </summary>
        internal static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمی‌توان پراپرتی {0} را یافت.
        /// </summary>
        internal static string CompareAttribute_UnknownProperty {
            get {
                return ResourceManager.GetString("CompareAttribute_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} حاوی شماره کارت اعتباری معتبر نیست.
        /// </summary>
        internal static string CreditCardAttribute_Invalid {
            get {
                return ResourceManager.GetString("CreditCardAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار برگشتی CustomValidationAttribute متد &apos;{0}&apos; از نوع &apos;{1}&apos; باید System.ComponentModel.DataAnnotations.ValidationResult باشد. برای بازگرداندن موفقیت System.ComponentModel.DataAnnotations.ValidationResult.Success را بازگردانید..
        /// </summary>
        internal static string CustomValidationAttribute_Method_Must_Return_ValidationResult {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Must_Return_ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متد CustomValidationAttribute &apos;{0}&apos; برای نوع &apos;{1}&apos; یا وجود ندارد یا public و static نیست.
        /// </summary>
        internal static string CustomValidationAttribute_Method_Not_Found {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار CustomValidationAttribute.Method مشخص نشده است.
        /// </summary>
        internal static string CustomValidationAttribute_Method_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute method &apos;{0}&apos; in type &apos;{1}&apos; must match the expected signature: public static ValidationResult {0}(object value, ValidationContext context).  The value can be strongly typed.  The ValidationContext parameter is optional..
        /// </summary>
        internal static string CustomValidationAttribute_Method_Signature {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع &apos;{0}&apos; به &apos;{1}&apos; به عنوان خروجی {2}.{3} تبدیل نمی شود..
        /// </summary>
        internal static string CustomValidationAttribute_Type_Conversion_Failed {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Conversion_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom validation نوع &apos;{0}&apos; باید public باشد..
        /// </summary>
        internal static string CustomValidationAttribute_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} معتبر نیست.
        /// </summary>
        internal static string CustomValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomValidationAttribute.ValidatorType مشخص نشده است.
        /// </summary>
        internal static string CustomValidationAttribute_ValidatorType_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidatorType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نوع داده نمی تواند خالی باشد.
        /// </summary>
        internal static string DataTypeAttribute_EmptyDataTypeString {
            get {
                return ResourceManager.GetString("DataTypeAttribute_EmptyDataTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پراپرتی {0} مقداردهی نشده، می توانید با متد {1} مقداردهی کنید.
        /// </summary>
        internal static string DisplayAttribute_PropertyNotSet {
            get {
                return ResourceManager.GetString("DisplayAttribute_PropertyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} فرمت صحیح یک ایمیل را ندارد.
        /// </summary>
        internal static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع انتخاب شده برای EnumDataTypeAttribute نمی‌تواند null باشد.
        /// </summary>
        internal static string EnumDataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} باید یکی از مقادیر تعیین شده باشد.
        /// </summary>
        internal static string EnumDataTypeAttribute_TypeNeedsToBeAnEnum {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeNeedsToBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} فقط می تواند فایل هایی با پسوند های {1} را بپذیرد.
        /// </summary>
        internal static string FileExtensionsAttribute_Invalid {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای بومی سازی برای پراپرتی &apos;{0}&apos;.
        ///نوع &apos;{1}&apos; یا public نیست یا حاوی یک public static string با نام &apos;{2}&apos; نیست.
        /// </summary>
        internal static string LocalizableString_LocalizationFailed {
            get {
                return ResourceManager.GetString("LocalizableString_LocalizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار MaxLengthAttribute باید بزرگتر از صفر باشد. استفاده از MaxLength() بدون مقدار ورودی یعنی نوشته ها می توانند بزگترین طول مجاز خود را داشته باشند..
        /// </summary>
        internal static string MaxLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر طول {0} می تواند {1} باشد.
        /// </summary>
        internal static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع متادیتا نمی تواند خالی باشد.
        /// </summary>
        internal static string MetadataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("MetadataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار MinLengthAttribute باید صفر یا بزرگتر از آن باشد.
        /// </summary>
        internal static string MinLengthAttribute_InvalidMinLength {
            get {
                return ResourceManager.GetString("MinLengthAttribute_InvalidMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل طول {0} می تواند {1} باشد.
        /// </summary>
        internal static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز جدید و تکرار آن یکی نیستند.
        /// </summary>
        internal static string New_Password_Not_Matched {
            get {
                return ResourceManager.GetString("New_Password_Not_Matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز و تکرار آن یکی نیستند.
        /// </summary>
        internal static string Password_Not_Matched {
            get {
                return ResourceManager.GetString("Password_Not_Matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} یک شماره تلفن معتبر نیست.
        /// </summary>
        internal static string PhoneAttribute_Invalid {
            get {
                return ResourceManager.GetString("PhoneAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع {0} باید implement {1}.
        /// </summary>
        internal static string RangeAttribute_ArbitraryTypeNotIComparable {
            get {
                return ResourceManager.GetString("RangeAttribute_ArbitraryTypeNotIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///بیشترین مقدار &apos;{0}&apos; باید بزرگتر یا مساوی کمترین مقدار &apos;{1}&apos; باشد.
        /// </summary>
        internal static string RangeAttribute_MinGreaterThanMax {
            get {
                return ResourceManager.GetString("RangeAttribute_MinGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار حداقل و حداکثر باید مشخص شوند.
        /// </summary>
        internal static string RangeAttribute_Must_Set_Min_And_Max {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Min_And_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگامی که string ها بیشترین و کمترین مقدار را به کار می برند باید OperandType تنظیم شود.
        /// </summary>
        internal static string RangeAttribute_Must_Set_Operand_Type {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Operand_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} باید بین {1} و {2} باشد.
        /// </summary>
        internal static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} باید با regular expression &apos;{1}&apos; منطبق باشد.
        /// </summary>
        internal static string RegexAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegexAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الگو باید حاوی یک الگوریتم صحیح باشد.
        /// </summary>
        internal static string RegularExpressionAttribute_Empty_Pattern {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute_Empty_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ضروری است.
        /// </summary>
        internal static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر طول باید غیر منفی باشد.
        /// </summary>
        internal static string StringLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("StringLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول {0} باید حداکثر {1} کاراکتر باشد.
        /// </summary>
        internal static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول {0} باید حداقل {2} و حداکثر {1} کاراکتر باشد.
        /// </summary>
        internal static string StringLengthAttribute_ValidationErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationErrorIncludingMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key parameter at position {0} with value &apos;{1}&apos; is not a string. Every key control parameter must be a string..
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyIsNotAString {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNotAString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key parameter at position {0} is null. Every key control parameter must be a string..
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyIsNull {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key parameter at position {0} with value &apos;{1}&apos; occurs more than once..
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyOccursMoreThanOnce {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyOccursMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of control parameters must be even..
        /// </summary>
        internal static string UIHintImplementation_NeedEvenNumberOfControlParameters {
            get {
                return ResourceManager.GetString("UIHintImplementation_NeedEvenNumberOfControlParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} حاوی یک آدرس صحیح http، https یا ftp نیست.
        /// </summary>
        internal static string UrlAttribute_Invalid {
            get {
                return ResourceManager.GetString("UrlAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید حداقل {2} و حداکثر {1} کاراکتر باشد..
        /// </summary>
        internal static string Validation_Min_Max_Length {
            get {
                return ResourceManager.GetString("Validation_Min_Max_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either ErrorMessageString or ErrorMessageResourceName must be set, but not both..
        /// </summary>
        internal static string ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource {
            get {
                return ResourceManager.GetString("ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsValid(object value) has not been implemented by this class.  The preferred entry point is GetValidationResult() and classes should override IsValid(object value, ValidationContext context)..
        /// </summary>
        internal static string ValidationAttribute_IsValid_NotImplemented {
            get {
                return ResourceManager.GetString("ValidationAttribute_IsValid_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both ErrorMessageResourceType and ErrorMessageResourceName need to be set on this attribute..
        /// </summary>
        internal static string ValidationAttribute_NeedBothResourceTypeAndResourceName {
            get {
                return ResourceManager.GetString("ValidationAttribute_NeedBothResourceTypeAndResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پراپرتی &apos;{0}&apos; ازresource type &apos;{1}&apos; از نوع string نیست.
        /// </summary>
        internal static string ValidationAttribute_ResourcePropertyNotStringType {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourcePropertyNotStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource type &apos;{0}&apos; does not have an accessible static property named &apos;{1}&apos;..
        /// </summary>
        internal static string ValidationAttribute_ResourceTypeDoesNotHaveProperty {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourceTypeDoesNotHaveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} نامعتبر است.
        /// </summary>
        internal static string ValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("ValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ValidationContext for the type &apos;{0}&apos;, member name &apos;{1}&apos; must provide the MethodInfo..
        /// </summary>
        internal static string ValidationContext_Must_Be_Method {
            get {
                return ResourceManager.GetString("ValidationContext_Must_Be_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service of type &apos;{0}&apos; already exists in the container..
        /// </summary>
        internal static string ValidationContextServiceContainer_ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ValidationContextServiceContainer_ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance provided must match the ObjectInstance on the ValidationContext supplied..
        /// </summary>
        internal static string Validator_InstanceMustMatchValidationContextInstance {
            get {
                return ResourceManager.GetString("Validator_InstanceMustMatchValidationContextInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار پراپرتی &apos;{0}&apos; باید از نوع &apos;{1}&apos; باشد.
        /// </summary>
        internal static string Validator_Property_Value_Wrong_Type {
            get {
                return ResourceManager.GetString("Validator_Property_Value_Wrong_Type", resourceCulture);
            }
        }
    }
}
